### ISSUE TITLE
@types/faker-js

### ISSUE THREAD

**Issue by marclundgren** [faker-javascript/faker#1]
**Is your feature request related to a problem? Please describe.**
I'm unable to use typescript with this library without creating my own type defs

**Describe the solution you'd like**
`npm i @types/faker-js` or something similar

**Additional context**

```
Could not find a declaration file for module '@faker-js/faker'. '$DIR/node_modules/@faker-js/faker/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/faker-js__faker` if it exists or add a new declaration (.d.ts) file containing `declare module '@faker-js/faker';`ts(7016)
```

**Comment by Awilum** [comment]
@marclundgren 
Can you please provide more information, what case do you have, that throws such kind of error ?

I have app.ts 

```js
import faker from '@fakerjs/faker';
console.log(faker.age());
```

When I compile it `tsc app.ts` I got no errors, it is compiled to app.js successfully

```js
"use strict";
exports.__esModule = true;
var faker_1 = require("@fakerjs/faker");
console.log(faker_1["default"].age());
```

**Comment by Awilum** [comment]
Please check 2.2.0 version
