### ISSUE TITLE
Consider Merging with `@faker-js`

### ISSUE THREAD

**Issue by damienwebdev** [faker-javascript/faker#2]
Hi! I'm Damien from the @faker-js team. I was just wondering if you had considered merging with `@faker-js/faker`. If not, more power to you, but I figure the more the merrier.

**Comment by Awilum** [comment]
Hello @damienwebdev 

My Faker Javascript is not a fork of FakerJS. 
I am building this project from scratch and in decoupled packages because the project will be significant growth.

Anyway,
Thank you for your proposal.

**Comment by JessicaSachs** [comment]
I'd like to just say for the record, we are also adding significant growth to the project, including a new roadmap. Please don't view this as a copy-and-paste. Thanks!

**Comment by prisis** [comment]
It's not fair, to delete and block a person without a reason... The message was pretty nice and clear described.

**Comment by junaga** [comment]
@prisis @Awilum is what we call an "individual"

**Comment by JoJk0** [comment]
It's just outright wrong for the community to have this package named like this. You will never achieve success with this package if you don't rename it... also it looks like it has been abandoned.
